# Generated by Django 5.2.16 on 2026-07-21 00:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notices', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='notice',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='notice',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='সক্রিয়'),
        ),
        migrations.AlterField(
            model_name='notice',
            name='title',
            field=models.CharField(db_index=True, max_length=255, verbose_name='শিরোনাম'),
        ),
        migrations.AddIndex(
            model_name='notice',
            index=models.Index(fields=['is_active', '-created_at'], name='notices_not_is_acti_5820df_idx'),
        ),
    ]
