# Generated by Django 5.2.16 on 2026-07-18 07:13

import django.contrib.auth.models
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('username', models.CharField(help_text='লগইনের জন্য ব্যবহার করা হবে', max_length=150, unique=True, verbose_name='ডাকনাম')),
                ('full_name', models.CharField(max_length=255, verbose_name='পূর্ণ নাম')),
                ('office_id', models.CharField(max_length=100, unique=True, verbose_name='অফিস আইডি')),
                ('designation', models.CharField(max_length=255, verbose_name='ডেজিগনেশন')),
                ('phone', models.CharField(max_length=20, verbose_name='ফোন')),
                ('blood_group', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=5, verbose_name='ব্লাড গ্রুপ')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='জন্ম তারিখ')),
                ('facebook_id', models.CharField(blank=True, default='', max_length=500, verbose_name='ফেসবুক আইডি')),
                ('is_admin', models.BooleanField(default=False, verbose_name='অ্যাডমিন')),
                ('is_founder', models.BooleanField(default=False, verbose_name='প্রতিষ্ঠাতা')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'ব্যবহারকারী',
                'verbose_name_plural': 'ব্যবহারকারীগণ',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ip_address', models.CharField(max_length=45)),
                ('device_info', models.CharField(blank=True, default='', max_length=255)),
                ('login_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('session_key', models.CharField(max_length=40, unique=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'সেশন',
                'verbose_name_plural': 'সেশনসমূহ',
            },
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['office_id'], name='accounts_us_office__1b5a14_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['phone'], name='accounts_us_phone_f54457_idx'),
        ),
        migrations.AddIndex(
            model_name='usersession',
            index=models.Index(fields=['user', 'is_active'], name='accounts_us_user_id_91ed82_idx'),
        ),
    ]
