# Generated by Django 5.2.16 on 2026-07-18 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='pending_approval',
            field=models.BooleanField(default=False, verbose_name='অনুমোদন বিহীন'),
        ),
    ]
