# Generated by Django 5.2.16 on 2026-07-21 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_siteconfig'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_admin',
            field=models.BooleanField(db_index=True, default=False, verbose_name='অ্যাডমিন'),
        ),
        migrations.AlterField(
            model_name='user',
            name='pending_approval',
            field=models.BooleanField(db_index=True, default=False, verbose_name='অনুমোদন বিহীন'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(db_index=True, max_length=20, verbose_name='ফোন'),
        ),
        migrations.AlterField(
            model_name='usersession',
            name='ip_address',
            field=models.CharField(db_index=True, max_length=45),
        ),
        migrations.AlterField(
            model_name='usersession',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['is_active', 'is_admin'], name='accounts_us_is_acti_fd1501_idx'),
        ),
        migrations.AddIndex(
            model_name='usersession',
            index=models.Index(fields=['-login_at'], name='accounts_us_login_a_2c6cd0_idx'),
        ),
    ]
