# Generated by Django 5.2.16 on 2026-07-25 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_is_admin_alter_user_pending_approval_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='siteconfig',
            options={'verbose_name': 'Site Configuration', 'verbose_name_plural': 'Site Configuration'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'The User', 'verbose_name_plural': 'Users'},
        ),
        migrations.AlterModelOptions(
            name='usersession',
            options={'verbose_name': 'Session', 'verbose_name_plural': 'Sessions'},
        ),
        migrations.AlterField(
            model_name='user',
            name='blood_group',
            field=models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=5, verbose_name='Blood Group'),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, verbose_name='Date Of Birth'),
        ),
        migrations.AlterField(
            model_name='user',
            name='designation',
            field=models.CharField(max_length=255, verbose_name='Designation'),
        ),
        migrations.AlterField(
            model_name='user',
            name='facebook_id',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='Facebook Id'),
        ),
        migrations.AlterField(
            model_name='user',
            name='full_name',
            field=models.CharField(max_length=255, verbose_name='Full Name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_admin',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Admin'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_founder',
            field=models.BooleanField(default=False, verbose_name='The Founder'),
        ),
        migrations.AlterField(
            model_name='user',
            name='office_id',
            field=models.CharField(max_length=100, unique=True, verbose_name='Office Id'),
        ),
        migrations.AlterField(
            model_name='user',
            name='pending_approval',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Unauthorized'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(db_index=True, max_length=20, verbose_name='The Phone'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(help_text='will be used for login', max_length=150, unique=True, verbose_name='Nickname'),
        ),
    ]
