# Generated by Django 5.2.16 on 2026-07-25 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_siteconfig_options_alter_user_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='siteconfig',
            options={'ordering': ['key'], 'verbose_name': 'Site Configuration', 'verbose_name_plural': 'Site Configuration'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['full_name'], 'verbose_name': 'The User', 'verbose_name_plural': 'Users'},
        ),
        migrations.AlterModelOptions(
            name='usersession',
            options={'ordering': ['-login_at'], 'verbose_name': 'Session', 'verbose_name_plural': 'Sessions'},
        ),
    ]
