# Generated by Django 5.2.16 on 2026-07-18 07:13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentListItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('list_date', models.DateField(verbose_name='তারিখ')),
                ('content', models.TextField(verbose_name='কন্টেন্ট')),
                ('source', models.CharField(choices=[('district', 'জেলা'), ('reuters', 'রয়টার্স'), ('social', 'সোশ্যাল মিডিয়া'), ('studio', 'স্টুডিও শুটিং')], max_length=20, verbose_name='সোর্স')),
                ('district', models.CharField(blank=True, default='', max_length=100, verbose_name='জেলা')),
                ('footage_source', models.CharField(choices=[('FTP', 'FTP'), ('WhatsApp', 'WhatsApp'), ('Gmail', 'Gmail'), ('Google Drive', 'Google Drive'), ('Ingest', 'Ingest'), ('Card', 'Card'), ('Studio shoot', 'Studio shoot')], max_length=50, verbose_name='ফুটেজ')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_list_items', to=settings.AUTH_USER_MODEL, verbose_name='যোগকারী')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'কন্টেন্ট তালিকা',
                'verbose_name_plural': 'কন্টেন্ট তালিকাসমূহ',
                'indexes': [models.Index(fields=['list_date'], name='contentlist_list_da_0a2b99_idx'), models.Index(fields=['source'], name='contentlist_source_eabda8_idx')],
            },
        ),
    ]
