# Generated by Django 5.2.16 on 2026-07-18 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contentlist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentlistitem',
            name='footage_source',
            field=models.CharField(blank=True, choices=[('FTP', 'FTP'), ('WhatsApp', 'WhatsApp'), ('Gmail', 'Gmail'), ('Google Drive', 'Google Drive'), ('Ingest', 'Ingest'), ('Card', 'Card'), ('Studio shoot', 'Studio shoot')], default='', max_length=50, null=True, verbose_name='ফুটেজ'),
        ),
    ]
