# Generated by Django 5.2.16 on 2026-07-21 00:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contentlist', '0002_alter_contentlistitem_footage_source'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentlistitem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='contentlistitem',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='contentlistitem',
            name='list_date',
            field=models.DateField(db_index=True, verbose_name='তারিখ'),
        ),
        migrations.AlterField(
            model_name='contentlistitem',
            name='source',
            field=models.CharField(choices=[('district', 'জেলা'), ('reuters', 'রয়টার্স'), ('social', 'সোশ্যাল মিডিয়া'), ('studio', 'স্টুডিও শুটিং')], db_index=True, max_length=20, verbose_name='সোর্স'),
        ),
        migrations.AddIndex(
            model_name='contentlistitem',
            index=models.Index(fields=['-list_date', '-created_at'], name='contentlist_list_da_461a8a_idx'),
        ),
    ]
