# Generated by Django 5.2.16 on 2026-07-21 02:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0003_alter_assignment_assign_date_and_more'),
        ('contentlist', '0003_alter_contentlistitem_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentlistitem',
            name='assignment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='content_list_items', to='assignments.assignment', verbose_name='এসাইনমেন্ট'),
        ),
    ]
