# Generated by Django 5.2.16 on 2026-07-25 18:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0006_add_reporter_name_hashtags_keywords_desc_special_note'),
        ('contentlist', '0005_alter_contentlistitem_footage_source'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contentlistitem',
            options={'verbose_name': 'Content Source', 'verbose_name_plural': 'Content Sources'},
        ),
        migrations.AlterField(
            model_name='contentlistitem',
            name='assignment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='content_list_items', to='assignments.assignment', verbose_name='Assignment'),
        ),
        migrations.AlterField(
            model_name='contentlistitem',
            name='content',
            field=models.TextField(verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='contentlistitem',
            name='district',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='District'),
        ),
        migrations.AlterField(
            model_name='contentlistitem',
            name='footage_source',
            field=models.CharField(blank=True, choices=[('FTP', 'FTP'), ('WhatsApp', 'WhatsApp'), ('Gmail', 'Gmail'), ('Google Drive', 'Google Drive'), ('Ingest', 'Ingest'), ('Card', 'Card'), ('Studio shoot', 'Studio shoot')], default='', max_length=50, verbose_name='Content Received By'),
        ),
        migrations.AlterField(
            model_name='contentlistitem',
            name='list_date',
            field=models.DateField(db_index=True, verbose_name='The Date'),
        ),
        migrations.AlterField(
            model_name='contentlistitem',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_list_items', to=settings.AUTH_USER_MODEL, verbose_name='Adder'),
        ),
        migrations.AlterField(
            model_name='contentlistitem',
            name='source',
            field=models.CharField(choices=[('District', 'District'), ('Reuters', 'Reuters'), ('Social', 'Social Media'), ('Studio', 'Studio Shooting')], db_index=True, max_length=20, verbose_name='Source'),
        ),
    ]
