# Generated by Django 5.2.16 on 2026-07-25 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contentlist', '0006_alter_contentlistitem_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contentlistitem',
            options={'ordering': ['-list_date', '-created_at'], 'verbose_name': 'Content Source', 'verbose_name_plural': 'Content Sources'},
        ),
    ]
