# Generated by Django 5.2.16 on 2026-07-18 07:13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sponsors', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('entry_date', models.DateField(verbose_name='তারিখ')),
                ('entry_time', models.TimeField(verbose_name='টাইম')),
                ('slug', models.CharField(max_length=255, verbose_name='কন্টেন্ট স্লাগ নেম')),
                ('headline', models.TextField(verbose_name='হেডলাইন')),
                ('links', models.JSONField(blank=True, default=dict, verbose_name='লিংকসমূহ')),
                ('comment', models.TextField(blank=True, default='', verbose_name='মন্তব্য')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_entries', to=settings.AUTH_USER_MODEL, verbose_name='আপলোডকারী')),
                ('sponsor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='content_entries', to='sponsors.sponsor', verbose_name='স্পন্সর')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'কন্টেন্ট এন্ট্রি',
                'verbose_name_plural': 'কন্টেন্ট এন্ট্রিসমূহ',
                'indexes': [models.Index(fields=['entry_date'], name='content_con_entry_d_722e52_idx'), models.Index(fields=['slug'], name='content_con_slug_b237de_idx'), models.Index(fields=['member', 'entry_date'], name='content_con_member__627fb5_idx')],
            },
        ),
    ]
