# Generated by Django 5.2.16 on 2026-07-21 00:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
        ('sponsors', '0002_alter_sponsor_created_at_alter_sponsor_deleted_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='contententry',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='contententry',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='contententry',
            name='entry_date',
            field=models.DateField(db_index=True, verbose_name='তারিখ'),
        ),
        migrations.AlterField(
            model_name='contententry',
            name='slug',
            field=models.CharField(db_index=True, max_length=255, verbose_name='কন্টেন্ট স্লাগ নেম'),
        ),
        migrations.AddIndex(
            model_name='contententry',
            index=models.Index(fields=['-entry_date', '-entry_time'], name='content_con_entry_d_451d91_idx'),
        ),
    ]
