# Generated by Django 5.2.16 on 2026-07-21 01:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_alter_contententry_created_at_and_more'),
    ]

    operations = [
    ]
