# Generated by Django 5.2.16 on 2026-07-21 02:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_add_assignment_to_contententry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contententry',
            name='assignment',
        ),
    ]
