# Generated by Django 5.2.16 on 2026-07-21 02:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_remove_add_assignment'),
    ]

    operations = [
    ]
