# Generated by Django 5.2.16 on 2026-07-21 02:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0003_alter_assignment_assign_date_and_more'),
        ('content', '0004_remove_add_assignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='contententry',
            name='assignment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='content_entries', to='assignments.assignment', verbose_name='এসাইনমেন্ট'),
        ),
    ]
