# Generated by Django 5.2.16 on 2026-07-21 06:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0003_alter_assignment_assign_date_and_more'),
        ('content', '0005_add_assignment_to_contententry_v2'),
        ('sponsors', '0003_remove_sponsor_sponsors_sp_name_f3b95f_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='contententry',
            name='content_con_slug_b237de_idx',
        ),
        migrations.AddConstraint(
            model_name='contententry',
            constraint=models.UniqueConstraint(fields=('slug', 'entry_date'), name='uq_content_slug_date'),
        ),
    ]
