# Generated by Django 5.2.16 on 2026-07-22 10:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0004_alter_assignment_options'),
        ('content', '0006_remove_contententry_content_con_slug_b237de_idx_and_more'),
        ('sponsors', '0004_add_language_field'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='contententry',
            name='language',
            field=models.CharField(choices=[('bn', 'বাংলা'), ('en', 'English')], db_index=True, default='bn', max_length=5, verbose_name='ভাষা'),
        ),
        migrations.AddIndex(
            model_name='contententry',
            index=models.Index(fields=['language'], name='content_con_languag_e6c20b_idx'),
        ),
    ]
