# Generated by Django 5.2.16 on 2026-07-25 18:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0007_add_language_field'),
        ('sponsors', '0005_add_reporter_name_hashtags_keywords_desc_special_note'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contententry',
            options={'verbose_name': 'Content Entry', 'verbose_name_plural': 'Content Entries'},
        ),
        migrations.AddField(
            model_name='contententry',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='contententry',
            name='hashtags',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='Hashtags'),
        ),
        migrations.AddField(
            model_name='contententry',
            name='keywords',
            field=models.TextField(blank=True, default='', verbose_name='Keywords'),
        ),
        migrations.AddField(
            model_name='contententry',
            name='reporter_name',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Reporter Name'),
        ),
        migrations.AddField(
            model_name='contententry',
            name='special_note',
            field=models.TextField(blank=True, default='', verbose_name='Special Note'),
        ),
        migrations.AlterField(
            model_name='contententry',
            name='comment',
            field=models.TextField(blank=True, default='', verbose_name='Comment'),
        ),
        migrations.AlterField(
            model_name='contententry',
            name='entry_date',
            field=models.DateField(db_index=True, verbose_name='The Date'),
        ),
        migrations.AlterField(
            model_name='contententry',
            name='entry_time',
            field=models.TimeField(verbose_name='Time'),
        ),
        migrations.AlterField(
            model_name='contententry',
            name='headline',
            field=models.TextField(verbose_name='The Headline'),
        ),
        migrations.AlterField(
            model_name='contententry',
            name='language',
            field=models.CharField(choices=[('Bn', 'Bangla'), ('en', 'English')], db_index=True, default='bn', max_length=5, verbose_name='The Language'),
        ),
        migrations.AlterField(
            model_name='contententry',
            name='links',
            field=models.JSONField(blank=True, default=dict, verbose_name='Links'),
        ),
        migrations.AlterField(
            model_name='contententry',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_entries', to=settings.AUTH_USER_MODEL, verbose_name='Uploader'),
        ),
        migrations.AlterField(
            model_name='contententry',
            name='slug',
            field=models.CharField(db_index=True, max_length=255, verbose_name='Content Slug Name'),
        ),
        migrations.AlterField(
            model_name='contententry',
            name='sponsor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='content_entries', to='sponsors.sponsor', verbose_name='Sponsor'),
        ),
    ]
