# Generated by Django 5.2.16 on 2026-07-25 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0008_add_reporter_name_hashtags_keywords_desc_special_note'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contententry',
            name='description',
        ),
        migrations.RemoveField(
            model_name='contententry',
            name='hashtags',
        ),
        migrations.RemoveField(
            model_name='contententry',
            name='keywords',
        ),
        migrations.RemoveField(
            model_name='contententry',
            name='reporter_name',
        ),
        migrations.RemoveField(
            model_name='contententry',
            name='special_note',
        ),
    ]
