# Generated by Django 5.2.16 on 2026-07-25 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0009_remove_contententry_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contententry',
            name='slug',
            field=models.CharField(blank=True, db_index=True, default='', max_length=255, verbose_name='Content Slug Name'),
        ),
    ]
