# Generated by Django 5.2.16 on 2026-07-25 19:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0010_make_slug_optional'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentDeletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platforms', models.CharField(blank=True, default='', max_length=255, verbose_name='Platform(s)')),
                ('deleted_at', models.DateTimeField(db_index=True, verbose_name='Deleted At')),
                ('instructed_by', models.CharField(blank=True, default='', max_length=255, verbose_name='Instructed By')),
                ('reason', models.TextField(blank=True, default='', verbose_name='Reason')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('content_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deletion_records', to='content.contententry', verbose_name='Content Entry')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_deletions', to=settings.AUTH_USER_MODEL, verbose_name='Recorded By')),
            ],
            options={
                'verbose_name': 'Content Deletion',
                'verbose_name_plural': 'Content Deletions',
                'ordering': ['-created_at'],
            },
        ),
    ]
