# Generated by Django 5.2.16 on 2026-07-25 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0011_add_contentdeletion_model'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contententry',
            options={'ordering': ['-entry_date', '-entry_time'], 'verbose_name': 'Content Entry', 'verbose_name_plural': 'Content Entries'},
        ),
    ]
