# Generated by Django 5.2.16 on 2026-08-02 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0012_add_model_ordering'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='contententry',
            name='uq_content_slug_date',
        ),
        migrations.AlterField(
            model_name='contententry',
            name='slug',
            field=models.CharField(db_index=True, max_length=255, verbose_name='Content Slug Name'),
        ),
    ]
