# Generated by Django 5.2.16 on 2026-07-21 02:41

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assignments', '0003_alter_assignment_assign_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AudioItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('audio_date', models.DateField(db_index=True, verbose_name='তারিখ')),
                ('title', models.CharField(max_length=255, verbose_name='শিরোনাম')),
                ('source', models.CharField(choices=[('district', 'জেলা'), ('reuters', 'রয়টার্স'), ('social', 'সোশ্যাল মিডিয়া'), ('studio', 'স্টুডিও শুটিং')], db_index=True, max_length=20, verbose_name='সোর্স')),
                ('district', models.CharField(blank=True, default='', max_length=100, verbose_name='জেলা')),
                ('duration', models.CharField(blank=True, default='', max_length=20, verbose_name='সময়কাল')),
                ('file_link', models.URLField(blank=True, default='', max_length=500, verbose_name='ফাইল লিংক')),
                ('voice_over', models.CharField(blank=True, default='', max_length=255, verbose_name='ভয়েস ওভার')),
                ('assignment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audio_items', to='assignments.assignment', verbose_name='এসাইনমেন্ট')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audio_items', to=settings.AUTH_USER_MODEL, verbose_name='যোগকারী')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'অডিও',
                'verbose_name_plural': 'অডিওসমূহ',
                'indexes': [models.Index(fields=['audio_date'], name='audio_audio_audio_d_e19e99_idx'), models.Index(fields=['source'], name='audio_audio_source_28495b_idx'), models.Index(fields=['-audio_date', '-created_at'], name='audio_audio_audio_d_4695e1_idx')],
            },
        ),
    ]
