# Generated by Django 5.2.16 on 2026-07-22 19:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0005_alter_assignment_options_and_more'),
        ('audio', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='audioitem',
            options={'ordering': ['-created_at'], 'verbose_name': 'Content', 'verbose_name_plural': 'Contents'},
        ),
        migrations.RemoveIndex(
            model_name='audioitem',
            name='audio_audio_audio_d_e19e99_idx',
        ),
        migrations.RemoveIndex(
            model_name='audioitem',
            name='audio_audio_source_28495b_idx',
        ),
        migrations.RemoveIndex(
            model_name='audioitem',
            name='audio_audio_audio_d_4695e1_idx',
        ),
        migrations.RemoveField(
            model_name='audioitem',
            name='audio_date',
        ),
        migrations.RemoveField(
            model_name='audioitem',
            name='district',
        ),
        migrations.RemoveField(
            model_name='audioitem',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='audioitem',
            name='file_link',
        ),
        migrations.RemoveField(
            model_name='audioitem',
            name='source',
        ),
        migrations.RemoveField(
            model_name='audioitem',
            name='title',
        ),
        migrations.RemoveField(
            model_name='audioitem',
            name='voice_over',
        ),
        migrations.AddField(
            model_name='audioitem',
            name='media_entries',
            field=models.JSONField(blank=True, default=list, verbose_name='Media Entries'),
        ),
        migrations.AlterField(
            model_name='audioitem',
            name='assignment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audio_items', to='assignments.assignment', verbose_name='Assignment'),
        ),
        migrations.AlterField(
            model_name='audioitem',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audio_items', to=settings.AUTH_USER_MODEL, verbose_name='Adder'),
        ),
    ]
