# Generated by Django 5.2.16 on 2026-07-25 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audio', '0002_alter_audioitem_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='audioitem',
            options={'ordering': ['-created_at'], 'verbose_name': 'Media Pool', 'verbose_name_plural': 'Media Pools'},
        ),
    ]
