# Generated by Django 5.2.16 on 2026-07-22 10:53

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='ছুটির ধরন')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='কোড')),
                ('days_per_year', models.PositiveSmallIntegerField(default=0, verbose_name='বার্ষিক ছুটির সংখ্যা')),
                ('carry_forward', models.BooleanField(default=False, verbose_name='জমা রাখা যাবে')),
                ('requires_approval', models.BooleanField(default=True, verbose_name='অনুমোদন প্রয়োজন')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='সক্রিয়')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='সাজানো')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'ছুটির ধরন',
                'verbose_name_plural': 'ছুটির ধরন সমূহ',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='শিফটের নাম')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='কোড')),
                ('start_time', models.TimeField(verbose_name='শ শুরুর সময়')),
                ('end_time', models.TimeField(verbose_name='শেষ সময়')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='সক্রিয়')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'শিফট',
                'verbose_name_plural': 'শিফট সমূহ',
                'ordering': ['start_time'],
            },
        ),
        migrations.CreateModel(
            name='LeaveRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_date', models.DateField(db_index=True, verbose_name='শুরুর তারিখ')),
                ('end_date', models.DateField(verbose_name='শেষ তারিখ')),
                ('total_days', models.PositiveSmallIntegerField(editable=False, verbose_name='মোট দিন')),
                ('reason', models.TextField(verbose_name='কারণ')),
                ('status', models.CharField(choices=[('pending', 'অপেক্ষমাণ'), ('approved', 'অনুমোদিত'), ('rejected', 'বাতিল'), ('cancelled', ' cancelled')], db_index=True, default='pending', max_length=20, verbose_name='অবস্থা')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='অনুমোদনের সময়')),
                ('rejection_reason', models.TextField(blank=True, verbose_name='বাতিলের কারণ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_leave_requests', to=settings.AUTH_USER_MODEL, verbose_name='অনুমোদনকারী')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hr_leaverequest_created', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_requests', to=settings.AUTH_USER_MODEL, verbose_name='কর্মচারী')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hr_leaverequest_updated', to=settings.AUTH_USER_MODEL)),
                ('leave_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='leave_requests', to='hr.leavetype', verbose_name='ছুটির ধরন')),
            ],
            options={
                'verbose_name': 'ছুটির আবেদন',
                'verbose_name_plural': 'ছুটির আবেদন সমূহ',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['employee', 'status'], name='hr_leavereq_employe_1b7929_idx'), models.Index(fields=['start_date', 'end_date'], name='hr_leavereq_start_d_9e9e54_idx')],
            },
        ),
        migrations.CreateModel(
            name='LeaveBalance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('year', models.PositiveSmallIntegerField(db_index=True, validators=[django.core.validators.MinValueValidator(2020), django.core.validators.MaxValueValidator(2099)], verbose_name='বছর')),
                ('total_days', models.DecimalField(decimal_places=1, max_digits=5, verbose_name='মোট দিন')),
                ('used_days', models.DecimalField(decimal_places=1, default=0, max_digits=5, verbose_name='ব্যবহৃত দিন')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_balances', to=settings.AUTH_USER_MODEL, verbose_name='কর্মচারী')),
                ('leave_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='balances', to='hr.leavetype', verbose_name='ছুটির ধরন')),
            ],
            options={
                'verbose_name': 'ছুটির ব্যালেন্স',
                'verbose_name_plural': 'ছুটির ব্যালেন্স',
                'ordering': ['employee', 'leave_type'],
                'unique_together': {('employee', 'leave_type', 'year')},
            },
        ),
        migrations.CreateModel(
            name='DutyRoster',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(db_index=True, verbose_name='তারিখ')),
                ('note', models.CharField(blank=True, max_length=500, verbose_name='নোট')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_rosters', to=settings.AUTH_USER_MODEL, verbose_name='নিয়োগকারী')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duty_rosters', to=settings.AUTH_USER_MODEL, verbose_name='কর্মচারী')),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rosters', to='hr.shift', verbose_name='শিফট')),
            ],
            options={
                'verbose_name': 'ডিউটি রোস্টার',
                'verbose_name_plural': 'ডিউটি রোস্টার',
                'ordering': ['-date', 'employee'],
                'indexes': [models.Index(fields=['date', 'shift'], name='hr_dutyrost_date_c68e50_idx')],
                'unique_together': {('employee', 'date')},
            },
        ),
    ]
