# Generated by Django 5.2.16 on 2026-07-25 05:37

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dutyroster',
            options={'ordering': ['-date', 'employee'], 'verbose_name': 'Duty Roster', 'verbose_name_plural': 'Duty Rosters'},
        ),
        migrations.AlterModelOptions(
            name='leavebalance',
            options={'ordering': ['employee', 'leave_type'], 'verbose_name': 'Leave Balance', 'verbose_name_plural': 'Leave Balances'},
        ),
        migrations.AlterModelOptions(
            name='leaverequest',
            options={'ordering': ['-created_at'], 'verbose_name': 'Leave Request', 'verbose_name_plural': 'Leave Requests'},
        ),
        migrations.AlterModelOptions(
            name='leavetype',
            options={'ordering': ['sort_order'], 'verbose_name': 'Leave Type', 'verbose_name_plural': 'Leave Types'},
        ),
        migrations.AlterModelOptions(
            name='shift',
            options={'ordering': ['start_time'], 'verbose_name': 'Shift', 'verbose_name_plural': 'Shifts'},
        ),
        migrations.AlterField(
            model_name='dutyroster',
            name='assigned_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_rosters', to=settings.AUTH_USER_MODEL, verbose_name='Assigned By'),
        ),
        migrations.AlterField(
            model_name='dutyroster',
            name='date',
            field=models.DateField(db_index=True, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='dutyroster',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duty_rosters', to=settings.AUTH_USER_MODEL, verbose_name='Employee'),
        ),
        migrations.AlterField(
            model_name='dutyroster',
            name='note',
            field=models.CharField(blank=True, max_length=500, verbose_name='Note'),
        ),
        migrations.AlterField(
            model_name='dutyroster',
            name='shift',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rosters', to='hr.shift', verbose_name='Shift'),
        ),
        migrations.AlterField(
            model_name='leavebalance',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_balances', to=settings.AUTH_USER_MODEL, verbose_name='Employee'),
        ),
        migrations.AlterField(
            model_name='leavebalance',
            name='leave_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='balances', to='hr.leavetype', verbose_name='Leave Type'),
        ),
        migrations.AlterField(
            model_name='leavebalance',
            name='total_days',
            field=models.DecimalField(decimal_places=1, max_digits=5, verbose_name='Total Days'),
        ),
        migrations.AlterField(
            model_name='leavebalance',
            name='used_days',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=5, verbose_name='Used Days'),
        ),
        migrations.AlterField(
            model_name='leavebalance',
            name='year',
            field=models.PositiveSmallIntegerField(db_index=True, validators=[django.core.validators.MinValueValidator(2020), django.core.validators.MaxValueValidator(2099)], verbose_name='Year'),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Approved At'),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_leave_requests', to=settings.AUTH_USER_MODEL, verbose_name='Approved By'),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_requests', to=settings.AUTH_USER_MODEL, verbose_name='Employee'),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='end_date',
            field=models.DateField(verbose_name='End Date'),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='leave_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='leave_requests', to='hr.leavetype', verbose_name='Leave Type'),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='reason',
            field=models.TextField(verbose_name='Reason'),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='rejection_reason',
            field=models.TextField(blank=True, verbose_name='Rejection Reason'),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='start_date',
            field=models.DateField(db_index=True, verbose_name='Start Date'),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='total_days',
            field=models.PositiveSmallIntegerField(editable=False, verbose_name='Total Days'),
        ),
        migrations.AlterField(
            model_name='leavetype',
            name='carry_forward',
            field=models.BooleanField(default=False, verbose_name='Carry Forward'),
        ),
        migrations.AlterField(
            model_name='leavetype',
            name='code',
            field=models.CharField(max_length=20, unique=True, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='leavetype',
            name='days_per_year',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Days Per Year'),
        ),
        migrations.AlterField(
            model_name='leavetype',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='leavetype',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Leave Type'),
        ),
        migrations.AlterField(
            model_name='leavetype',
            name='requires_approval',
            field=models.BooleanField(default=True, verbose_name='Requires Approval'),
        ),
        migrations.AlterField(
            model_name='leavetype',
            name='sort_order',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Sort Order'),
        ),
        migrations.AlterField(
            model_name='shift',
            name='code',
            field=models.CharField(max_length=10, unique=True, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='shift',
            name='end_time',
            field=models.TimeField(verbose_name='End Time'),
        ),
        migrations.AlterField(
            model_name='shift',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='shift',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Shift Name'),
        ),
        migrations.AlterField(
            model_name='shift',
            name='start_time',
            field=models.TimeField(verbose_name='Start Time'),
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(db_index=True, verbose_name='Date')),
                ('check_in', models.DateTimeField(blank=True, null=True, verbose_name='Check In')),
                ('check_out', models.DateTimeField(blank=True, null=True, verbose_name='Check Out')),
                ('status', models.CharField(choices=[('present', 'Present'), ('late', 'Late'), ('half_day', 'Half Day')], default='present', max_length=20, verbose_name='Status')),
                ('note', models.CharField(blank=True, max_length=500, verbose_name='Note')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to=settings.AUTH_USER_MODEL, verbose_name='Employee')),
                ('shift', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendances', to='hr.shift', verbose_name='Shift')),
            ],
            options={
                'verbose_name': 'Attendance',
                'verbose_name_plural': 'Attendance Records',
                'ordering': ['-date', 'employee'],
                'indexes': [models.Index(fields=['date', 'status'], name='hr_attendan_date_36f853_idx'), models.Index(fields=['employee', 'date'], name='hr_attendan_employe_c63029_idx')],
                'unique_together': {('employee', 'date')},
            },
        ),
    ]
