# Generated by Django 5.2.16 on 2026-07-25 09:32

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0002_attendance_model'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='dutyroster',
            unique_together={('employee', 'date', 'shift')},
        ),
    ]
