# Generated by Django 5.2.16 on 2026-08-03 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0003_alter_dutyroster_unique_together'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Attendance',
        ),
    ]
