from django.urls import path
from . import views
from . import admin_views

app_name = 'cms'

urlpatterns = [
    path('login/', views.cms_login, name='cms-login'),
    path('', views.cms_dashboard, name='cms-dashboard'),
    path('dashboard/', views.dashboard_tab, name='cms-dashboard-tab'),
    path('entries/new/', views.new_entry_tab, name='cms-new-entry'),
    path('entries/', views.all_entries_tab, name='cms-all-entries'),
    path('entries/save/', views.save_entry, name='cms-save-entry'),
    path('entries/<hexuuid:pk>/edit/', views.edit_entry, name='cms-edit-entry'),
    path('entries/<hexuuid:pk>/duplicate/', views.duplicate_entry, name='cms-duplicate-entry'),
    path('entries/<hexuuid:pk>/delete/', views.delete_entry, name='cms-delete-entry'),
    path('sponsors/', views.sponsors_tab, name='cms-sponsors'),
    path('sponsors/save/', views.save_sponsor, name='cms-save-sponsor'),
    path('sponsors/<hexuuid:pk>/edit/', views.edit_sponsor, name='cms-edit-sponsor'),
    path('sponsors/<hexuuid:pk>/delete/', views.delete_sponsor, name='cms-delete-sponsor'),
    path('leaderboard/', views.leaderboard_tab, name='cms-leaderboard'),
    path('leaderboard/<uuid:user_id>/', views.cms_leaderboard_detail, name='cms-leaderboard-detail'),
    path('admin-panel/', views.admin_panel_tab, name='cms-admin'),
    path('admin-panel/audit/', admin_views.admin_audit_log, name='cms-admin-audit'),
    path('admin-panel/health/', admin_views.admin_system_health, name='cms-admin-health'),
    path('admin-panel/settings/', admin_views.admin_settings, name='cms-admin-settings'),
    path('admin-panel/activity/', admin_views.admin_activity_timeline, name='cms-admin-activity'),
    path('admin-panel/bulk-delete/', admin_views.admin_bulk_delete, name='cms-admin-bulk-delete'),
    path('admin-panel/csv-import/', admin_views.admin_csv_import, name='cms-admin-csv-import'),
    path('admin-panel/<uuid:user_id>/reset-password/', views.cms_admin_reset_password, name='cms-admin-reset-pw'),
    path('admin-panel/users/add/', views.cms_admin_add_user, name='cms-admin-add-user'),
    path('admin-panel/users/<uuid:user_id>/toggle-admin/', views.cms_admin_toggle_admin, name='cms-admin-toggle-admin'),
    path('admin-panel/users/<uuid:user_id>/delete/', views.cms_admin_delete_user, name='cms-admin-delete-user'),
    path('admin-panel/sessions/<uuid:session_id>/logout/', views.cms_admin_logout_session, name='cms-admin-logout-session'),
    path('logout/', views.cms_logout, name='cms-logout'),
    path('widgets/leaderboard/', views.leaderboard_widget, name='cms-widget-leaderboard'),
    path('widgets/sponsor-track/', views.sponsor_track_widget, name='cms-widget-sponsor'),
    path('widgets/contributors/', views.contributors_widget, name='cms-widget-contributors'),
    path('password-reset/', views.cms_password_reset_request, name='cms-password-reset'),
    path('password-reset/confirm/', views.cms_password_reset_confirm, name='cms-password-reset-confirm'),
    path('notices/', views.notices_tab, name='cms-notices-tab'),
    path('notices/create/', views.create_notice, name='cms-create-notice'),
    path('notices/<hexuuid:pk>/', views.notice_detail, name='cms-notice-detail'),
    path('notices/<hexuuid:pk>/delete/', views.delete_notice, name='cms-delete-notice'),
    path('register/', views.cms_register, name='cms-register'),
    path('admin-panel/users/<uuid:user_id>/approve/', views.approve_registration, name='cms-approve-registration'),
    path('admin-panel/users/<uuid:user_id>/reject/', views.reject_registration, name='cms-reject-registration'),
    path('admin-panel/users/<uuid:user_id>/edit/', views.user_edit_tab, name='cms-user-edit'),
    path('admin-panel/users/<uuid:user_id>/detail/', views.user_detail_tab, name='cms-user-detail'),
    path('admin-panel/roles/', views.roles_tab, name='cms-roles'),
    path('admin-panel/roles/save/', views.save_role, name='cms-save-role'),
    path('admin-panel/roles/<int:pk>/edit/', views.edit_role, name='cms-edit-role'),
    path('admin-panel/roles/<int:pk>/delete/', views.delete_role, name='cms-delete-role'),
    path('archive/', views.archive_tab, name='cms-archive'),
    path('archive/<slug:module>/<hexuuid:pk>/', views.archive_view_item, name='cms-archive-view'),
    path('deleted-data/', views.deleted_data_tab, name='cms-deleted-data'),
    path('deleted-data/restore/', views.restore_deleted_item, name='cms-restore-deleted'),
    # ─── Content Deletion ───
    path('content-deletion/', views.content_deletion_tab, name='cms-content-deletion'),
    path('content-deletion/save/', views.save_content_deletion, name='cms-save-content-deletion'),
    path('content-deletion/<int:pk>/delete/', views.delete_content_deletion, name='cms-delete-content-deletion'),
    path('reports/', views.reports_tab, name='cms-reports'),
    path('reports/builder/', views.report_builder, name='cms-report-builder'),
    path('reports/builder/<hexuuid:pk>/', views.report_builder, name='cms-report-edit'),
    path('reports/<hexuuid:pk>/delete/', views.report_delete, name='cms-report-delete'),
    path('reports/<hexuuid:pk>/run/', views.report_run, name='cms-report-run'),
    path('reports/<hexuuid:pk>/csv/', views.report_export_csv, name='cms-report-csv'),
    path('reports/<hexuuid:pk>/pdf/', views.report_export_pdf, name='cms-report-pdf'),
    # ─── Duty Roster ───
    path('roster/', views.roster_tab, name='cms-roster'),
    path('roster/save/', views.roster_save, name='cms-roster-save'),
    path('roster/day/edit/', views.roster_day_edit, name='cms-roster-day-edit'),
    path('roster/day/save/', views.roster_day_save, name='cms-roster-day-save'),
    path('roster/<hexuuid:pk>/delete/', views.roster_delete, name='cms-roster-delete'),
    path('roster/weekly-builder/', views.roster_weekly_builder, name='cms-roster-weekly-builder'),
    path('roster/weekly-builder/save/', views.roster_weekly_builder_save, name='cms-roster-weekly-builder-save'),
    path('roster/shifts/', views.shift_manage_tab, name='cms-shift-manage'),
    path('roster/shifts/save/', views.shift_save, name='cms-shift-save'),
    path('roster/shifts/<hexuuid:pk>/toggle/', views.shift_toggle, name='cms-shift-toggle'),
    path('roster/shifts/<hexuuid:pk>/delete/', views.shift_delete, name='cms-shift-delete'),
    path('my-roster/', views.my_roster_tab, name='cms-my-roster'),

    # ─── Leave Management ───
    path('leave/', views.leave_tab, name='cms-leave'),
    path('leave/save/', views.leave_save, name='cms-leave-save'),
    path('leave/admin/', views.leave_admin_tab, name='cms-leave-admin'),
    path('leave-admin/', views.leave_admin_tab, name='cms-leave-admin-alias'),
    path('leave/<hexuuid:pk>/approve/', views.leave_approve, name='cms-leave-approve'),
    path('leave/balances/', views.leave_balances_tab, name='cms-leave-balances'),
    path('leave/balances/save/', views.leave_balance_save, name='cms-leave-balance-save'),
    path('leave/types/', views.leave_types_tab, name='cms-leave-types'),
    path('leave/types/save/', views.leave_type_save, name='cms-leave-type-save'),
    path('leave/types/<hexuuid:pk>/delete/', views.leave_type_delete, name='cms-leave-type-delete'),
]

