from django.urls import path
from . import views
from . import admin_views

app_name = 'cms'

urlpatterns = [
    path('login/', views.cms_login, name='cms-login'),
    path('', views.cms_dashboard, name='cms-dashboard'),
    path('dashboard/', views.dashboard_tab, name='cms-dashboard-tab'),
    path('entries/new/', views.new_entry_tab, name='cms-new-entry'),
    path('entries/', views.all_entries_tab, name='cms-all-entries'),
    path('entries/save/', views.save_entry, name='cms-save-entry'),
    path('entries/<hexuuid:pk>/edit/', views.edit_entry, name='cms-edit-entry'),
    path('entries/<hexuuid:pk>/duplicate/', views.duplicate_entry, name='cms-duplicate-entry'),
    path('entries/<hexuuid:pk>/delete/', views.delete_entry, name='cms-delete-entry'),
    path('sponsors/', views.sponsors_tab, name='cms-sponsors'),
    path('sponsors/save/', views.save_sponsor, name='cms-save-sponsor'),
    path('sponsors/<hexuuid:pk>/edit/', views.edit_sponsor, name='cms-edit-sponsor'),
    path('sponsors/<hexuuid:pk>/delete/', views.delete_sponsor, name='cms-delete-sponsor'),
    path('content-lists/', views.content_list_tab, name='cms-content-list'),
    path('content-lists/save/', views.save_content_list, name='cms-save-content-list'),
    path('content-lists/<hexuuid:pk>/view/', views.view_content_list, name='cms-view-content-list'),
    path('content-lists/<hexuuid:pk>/edit/', views.edit_content_list, name='cms-edit-content-list'),
    path('content-lists/<hexuuid:pk>/delete/', views.delete_content_list, name='cms-delete-content-list'),
    path('audio/', views.audio_tab, name='cms-audio'),
    path('audio/save/', views.save_audio, name='cms-save-audio'),
    path('audio/<hexuuid:pk>/edit/', views.edit_audio, name='cms-edit-audio'),
    path('audio/<hexuuid:pk>/delete/', views.delete_audio, name='cms-delete-audio'),
    path('final-packages/', views.final_package_tab, name='cms-final-packages'),
    path('final-packages/save/', views.save_final_package, name='cms-save-final-package'),
    path('final-packages/<hexuuid:pk>/view/', views.final_package_detail, name='cms-view-final-package'),
    path('final-packages/<hexuuid:pk>/edit/', views.edit_final_package, name='cms-edit-final-package'),
    path('final-packages/<hexuuid:pk>/delete/', views.delete_final_package, name='cms-delete-final-package'),
    path('assignments/', views.assignments_tab, name='cms-assignments'),
    path('assignments/save/', views.save_assignment, name='cms-save-assignment'),
    path('assignments/<hexuuid:pk>/view/', views.view_assignment, name='cms-view-assignment'),
    path('assignments/<hexuuid:pk>/edit/', views.edit_assignment, name='cms-edit-assignment'),
    path('assignments/<hexuuid:pk>/delete/', views.delete_assignment, name='cms-delete-assignment'),
    path('scripts/', views.scripts_tab, name='cms-scripts'),
    path('scripts/new/', views.new_script_tab, name='cms-new-script'),
    path('scripts/save/', views.save_script, name='cms-save-script'),
    path('scripts/<hexuuid:pk>/', views.script_detail, name='cms-script-detail'),
    path('scripts/<hexuuid:pk>/edit/', views.edit_script, name='cms-edit-script'),
    path('scripts/<hexuuid:pk>/submit/', views.submit_script, name='cms-submit-script'),
    path('scripts/<hexuuid:pk>/approve/', views.approve_script, name='cms-approve-script'),
    path('scripts/<hexuuid:pk>/reject/', views.reject_script, name='cms-reject-script'),
    path('scripts/<hexuuid:pk>/delete/', views.delete_script, name='cms-delete-script'),
    path('assignments/<hexuuid:pk>/status/', views.update_assignment_status, name='cms-assignment-status'),
    path('leaderboard/', views.leaderboard_tab, name='cms-leaderboard'),
    path('leaderboard/<uuid:user_id>/', views.cms_leaderboard_detail, name='cms-leaderboard-detail'),
    path('admin-panel/', views.admin_panel_tab, name='cms-admin'),
    path('admin-panel/audit/', admin_views.admin_audit_log, name='cms-admin-audit'),
    path('admin-panel/health/', admin_views.admin_system_health, name='cms-admin-health'),
    path('admin-panel/settings/', admin_views.admin_settings, name='cms-admin-settings'),
    path('admin-panel/activity/', admin_views.admin_activity_timeline, name='cms-admin-activity'),
    path('admin-panel/bulk-delete/', admin_views.admin_bulk_delete, name='cms-admin-bulk-delete'),
    path('admin-panel/csv-import/', admin_views.admin_csv_import, name='cms-admin-csv-import'),
    path('admin-panel/<uuid:user_id>/reset-password/', views.cms_admin_reset_password, name='cms-admin-reset-pw'),
    path('admin-panel/users/add/', views.cms_admin_add_user, name='cms-admin-add-user'),
    path('admin-panel/users/<uuid:user_id>/toggle-admin/', views.cms_admin_toggle_admin, name='cms-admin-toggle-admin'),
    path('admin-panel/users/<uuid:user_id>/delete/', views.cms_admin_delete_user, name='cms-admin-delete-user'),
    path('admin-panel/sessions/<uuid:session_id>/logout/', views.cms_admin_logout_session, name='cms-admin-logout-session'),
    path('logout/', views.cms_logout, name='cms-logout'),
    path('widgets/leaderboard/', views.leaderboard_widget, name='cms-widget-leaderboard'),
    path('widgets/sponsor-track/', views.sponsor_track_widget, name='cms-widget-sponsor'),
    path('widgets/contributors/', views.contributors_widget, name='cms-widget-contributors'),
    path('password-reset/', views.cms_password_reset_request, name='cms-password-reset'),
    path('password-reset/confirm/', views.cms_password_reset_confirm, name='cms-password-reset-confirm'),
    path('notices/', views.notices_tab, name='cms-notices-tab'),
    path('notices/create/', views.create_notice, name='cms-create-notice'),
    path('notices/<hexuuid:pk>/', views.notice_detail, name='cms-notice-detail'),
    path('notices/<hexuuid:pk>/delete/', views.delete_notice, name='cms-delete-notice'),
    path('register/', views.cms_register, name='cms-register'),
    path('admin-panel/users/<uuid:user_id>/approve/', views.approve_registration, name='cms-approve-registration'),
    path('admin-panel/users/<uuid:user_id>/reject/', views.reject_registration, name='cms-reject-registration'),
    path('admin-panel/users/<uuid:user_id>/edit/', views.user_edit_tab, name='cms-user-edit'),
    path('admin-panel/users/<uuid:user_id>/detail/', views.user_detail_tab, name='cms-user-detail'),
    path('admin-panel/roles/', views.roles_tab, name='cms-roles'),
    path('admin-panel/roles/save/', views.save_role, name='cms-save-role'),
    path('admin-panel/roles/<int:pk>/edit/', views.edit_role, name='cms-edit-role'),
    path('admin-panel/roles/<int:pk>/delete/', views.delete_role, name='cms-delete-role'),
    path('archive/', views.archive_tab, name='cms-archive'),
    path('reports/', views.reports_tab, name='cms-reports'),
    path('reports/builder/', views.report_builder, name='cms-report-builder'),
    path('reports/builder/<hexuuid:pk>/', views.report_builder, name='cms-report-edit'),
    path('reports/<hexuuid:pk>/delete/', views.report_delete, name='cms-report-delete'),
    path('reports/<hexuuid:pk>/run/', views.report_run, name='cms-report-run'),
    path('reports/<hexuuid:pk>/csv/', views.report_export_csv, name='cms-report-csv'),
    path('reports/<hexuuid:pk>/pdf/', views.report_export_pdf, name='cms-report-pdf'),
    # ─── Duty Roster ───
    path('roster/', views.roster_tab, name='cms-roster'),
    path('roster/save/', views.roster_save, name='cms-roster-save'),
    path('my-roster/', views.my_roster_tab, name='cms-my-roster'),

    # ─── Leave Management ───
    path('leave/', views.leave_tab, name='cms-leave'),
    path('leave/save/', views.leave_save, name='cms-leave-save'),
    path('leave/admin/', views.leave_admin_tab, name='cms-leave-admin'),
    path('leave-admin/', views.leave_admin_tab, name='cms-leave-admin-alias'),
    path('leave/<hexuuid:pk>/approve/', views.leave_approve, name='cms-leave-approve'),
]

