# Generated by Django 5.2.16 on 2026-07-18 07:13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=255, verbose_name='স্পন্সরের নাম')),
                ('daily_quota', models.IntegerField(verbose_name='প্রতিদিন কয়টা')),
                ('total_quota', models.IntegerField(verbose_name='মোট কয়টা')),
                ('start_date', models.DateField(verbose_name='শুরুর তারিখ')),
                ('end_date', models.DateField(verbose_name='শেষ তারিখ')),
                ('content_type', models.CharField(blank=True, default='', max_length=255, verbose_name='কন্টেন্ট টাইপ')),
                ('has_doggy', models.BooleanField(default=False, verbose_name='ডগি (FT)')),
                ('has_popup', models.BooleanField(default=False, verbose_name='পপআপ x2')),
                ('has_tvc', models.BooleanField(default=False, verbose_name='টিভিসি x1')),
                ('has_gpi', models.BooleanField(default=False, verbose_name='জিপিআই x1')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'স্পন্সর',
                'verbose_name_plural': 'স্পন্সরগণ',
                'indexes': [models.Index(fields=['start_date', 'end_date'], name='sponsors_sp_start_d_85e290_idx')],
            },
        ),
    ]
