# Generated by Django 5.2.16 on 2026-07-21 00:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sponsors', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='sponsor',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='end_date',
            field=models.DateField(db_index=True, verbose_name='শেষ তারিখ'),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='name',
            field=models.CharField(db_index=True, max_length=255, verbose_name='স্পন্সরের নাম'),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='start_date',
            field=models.DateField(db_index=True, verbose_name='শুরুর তারিখ'),
        ),
        migrations.AddIndex(
            model_name='sponsor',
            index=models.Index(fields=['name'], name='sponsors_sp_name_f3b95f_idx'),
        ),
    ]
