# Generated by Django 5.2.16 on 2026-07-21 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sponsors', '0002_alter_sponsor_created_at_alter_sponsor_deleted_at_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='sponsor',
            name='sponsors_sp_name_f3b95f_idx',
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='স্পন্সরের নাম'),
        ),
    ]
