# Generated by Django 5.2.16 on 2026-07-22 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sponsors', '0003_remove_sponsor_sponsors_sp_name_f3b95f_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sponsor',
            name='has_doggy',
            field=models.BooleanField(db_index=True, default=False, verbose_name='ডগি (FT)'),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='has_gpi',
            field=models.BooleanField(db_index=True, default=False, verbose_name='জিপিআই x1'),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='has_popup',
            field=models.BooleanField(db_index=True, default=False, verbose_name='পপআপ x2'),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='has_tvc',
            field=models.BooleanField(db_index=True, default=False, verbose_name='টিভিসি x1'),
        ),
    ]
