# Generated by Django 5.2.16 on 2026-07-25 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sponsors', '0004_add_language_field'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sponsor',
            options={'verbose_name': 'Sponsor', 'verbose_name_plural': 'Sponsors'},
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='content_type',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Content Type'),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='daily_quota',
            field=models.IntegerField(verbose_name='how many per day'),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='end_date',
            field=models.DateField(db_index=True, verbose_name='Last Date'),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='has_doggy',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Dougie (Ft)'),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='has_gpi',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Gpi X1'),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='has_popup',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Popup X2'),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='has_tvc',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Tvc X1'),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name="Sponsor's Name"),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='start_date',
            field=models.DateField(db_index=True, verbose_name='Start Date'),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='total_quota',
            field=models.IntegerField(verbose_name='how many in total'),
        ),
    ]
