# Generated by Django 5.2.16 on 2026-07-25 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sponsors', '0005_add_reporter_name_hashtags_keywords_desc_special_note'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sponsor',
            options={'ordering': ['name'], 'verbose_name': 'Sponsor', 'verbose_name_plural': 'Sponsors'},
        ),
    ]
