# Generated by Django 5.2.16 on 2026-07-18 07:13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('assign_date', models.DateField(verbose_name='তারিখ')),
                ('caption', models.TextField(verbose_name='কন্টেন্ট ক্যাপশন')),
                ('source_link', models.URLField(blank=True, default='', max_length=500, verbose_name='সোর্স লিংক')),
                ('district', models.CharField(blank=True, default='', max_length=100, verbose_name='জেলা')),
                ('reporter', models.CharField(max_length=255, verbose_name='রিপোর্টারের নাম')),
                ('status', models.CharField(choices=[('Assigned', 'Assigned'), ('Processing', 'Processing'), ('Done', 'Done'), ('Cancel', 'Cancel')], default='Assigned', max_length=20, verbose_name='স্ট্যাটাস')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to=settings.AUTH_USER_MODEL, verbose_name='এসাইনকারী')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'এসাইনমেন্ট',
                'verbose_name_plural': 'এসাইনমেন্টসমূহ',
                'indexes': [models.Index(fields=['assign_date'], name='assignments_assign__a68f97_idx'), models.Index(fields=['status'], name='assignments_status_63bdfc_idx'), models.Index(fields=['reporter'], name='assignments_reporte_6e8f8b_idx')],
            },
        ),
    ]
