# Generated by Django 5.2.16 on 2026-07-21 00:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0002_assignment_reporter_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='assign_date',
            field=models.DateField(db_index=True, verbose_name='তারিখ'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='reporter',
            field=models.CharField(db_index=True, max_length=255, verbose_name='রিপোর্টারের নাম'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='status',
            field=models.CharField(choices=[('Assigned', 'Assigned'), ('Processing', 'Processing'), ('Done', 'Done'), ('Cancel', 'Cancel')], db_index=True, default='Assigned', max_length=20, verbose_name='স্ট্যাটাস'),
        ),
        migrations.AddIndex(
            model_name='assignment',
            index=models.Index(fields=['-assign_date', '-created_at'], name='assignments_assign__a5d9d9_idx'),
        ),
    ]
