# Generated by Django 5.2.16 on 2026-07-22 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0003_alter_assignment_assign_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assignment',
            options={'ordering': ['-assign_date', '-created_at'], 'verbose_name': 'এসাইনমেন্ট', 'verbose_name_plural': 'এসাইনমেন্টসমূহ'},
        ),
    ]
