# Generated by Django 5.2.16 on 2026-07-22 19:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0004_alter_assignment_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assignment',
            options={'ordering': ['-assign_date', '-created_at'], 'verbose_name': 'Assignment', 'verbose_name_plural': 'Assignments'},
        ),
        migrations.AlterField(
            model_name='assignment',
            name='assign_date',
            field=models.DateField(db_index=True, verbose_name='The Date'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='caption',
            field=models.TextField(verbose_name='Content Caption'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='district',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='District'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to=settings.AUTH_USER_MODEL, verbose_name='Assignor'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='reporter',
            field=models.CharField(db_index=True, max_length=255, verbose_name='Reporterের নাম'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='reporter_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_assignments', to=settings.AUTH_USER_MODEL, verbose_name='Reporter (User)'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='source_link',
            field=models.URLField(blank=True, default='', max_length=500, verbose_name='Source Link'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='status',
            field=models.CharField(choices=[('Assigned', 'Assigned'), ('Processing', 'Processing'), ('Done', 'Done'), ('Cancel', 'Cancel')], db_index=True, default='Assigned', max_length=20, verbose_name='Status'),
        ),
    ]
