# Generated by Django 5.2.16 on 2026-07-25 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0005_alter_assignment_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='reporter',
            field=models.CharField(db_index=True, max_length=255, verbose_name='Reporter Name'),
        ),
    ]
