# Generated by Django 5.2.16 on 2026-07-25 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0002_alter_auditlog_action_alter_auditlog_content_type_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auditlog',
            options={'ordering': ['-created_at'], 'verbose_name': 'Audit Log', 'verbose_name_plural': 'Audit Logs'},
        ),
    ]
