# Generated by Django 5.2.16 on 2026-07-21 05:23

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('module', models.CharField(choices=[('entries', 'Content Entries'), ('assignments', 'Assignments'), ('scripts', 'Digital Scripts'), ('audio', 'Audio'), ('contentlist', 'Content List'), ('finalpackage', 'Final Packages'), ('sponsors', 'Sponsors'), ('users', 'Users')], max_length=30)),
                ('aggregation', models.CharField(choices=[('list', 'Detailed List'), ('count', 'Total Count'), ('status_breakdown', 'Status Breakdown'), ('member_breakdown', 'By Member'), ('source_breakdown', 'By Source'), ('sponsor_breakdown', 'By Sponsor'), ('daily_trend', 'Daily Trend'), ('monthly_trend', 'Monthly Trend'), ('district_breakdown', 'By District')], default='list', max_length=30)),
                ('period', models.CharField(choices=[('today', 'Today'), ('yesterday', 'Yesterday'), ('this_week', 'This Week'), ('last_week', 'Last Week'), ('this_month', 'This Month'), ('last_month', 'Last Month'), ('this_quarter', 'This Quarter'), ('this_year', 'This Year'), ('custom', 'Custom Range')], default='this_month', max_length=20)),
                ('date_from', models.DateField(blank=True, null=True)),
                ('date_to', models.DateField(blank=True, null=True)),
                ('filters', models.JSONField(blank=True, default=dict, help_text='Extra filters as JSON')),
                ('show_chart', models.CharField(choices=[('none', 'No Chart'), ('bar', 'Bar Chart'), ('pie', 'Pie Chart'), ('line', 'Line Chart')], default='none', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_configs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'report_config',
                'ordering': ['-updated_at'],
            },
        ),
    ]
