# Generated by Django 5.2.16 on 2026-07-25 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportconfig',
            name='module',
            field=models.CharField(choices=[('entries', 'Content Entries'), ('assignments', 'Assignments'), ('scripts', 'Digital Scripts'), ('audio', 'Media Pool'), ('contentlist', 'Content Sources'), ('finalpackage', 'Final Packages'), ('sponsors', 'Sponsors'), ('users', 'Users')], max_length=30),
        ),
    ]
