# Generated by Django 5.2.16 on 2026-07-18 07:13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Script',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('script_date', models.DateField(verbose_name='তারিখ')),
                ('headline', models.CharField(max_length=255, verbose_name='সম্ভাব্য হেডলাইন')),
                ('source', models.CharField(choices=[('district', 'জেলা'), ('reuters', 'রয়টার্স'), ('social', 'সোশ্যাল মিডিয়া'), ('studio', 'স্টুডিও শুটিং')], max_length=20, verbose_name='কন্টেন্ট সোর্স')),
                ('district', models.CharField(blank=True, default='', max_length=100, verbose_name='জেলার নাম')),
                ('district_reporter', models.CharField(blank=True, default='', max_length=255, verbose_name='জেলার রিপোর্টার')),
                ('body', models.TextField(blank=True, default='', verbose_name='স্ক্রিপ্ট')),
                ('status', models.CharField(choices=[('draft', 'খসড়া'), ('pending', 'অনুমোদনের অপেক্ষায়'), ('approved', 'অনুমোদিত')], default='draft', max_length=20, verbose_name='স্ট্যাটাস')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='অনুমোদনের সময়')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_scripts', to=settings.AUTH_USER_MODEL, verbose_name='অনুমোদনকারী')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('writer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scripts', to=settings.AUTH_USER_MODEL, verbose_name='স্ক্রিপ্ট রাইটার')),
            ],
            options={
                'verbose_name': 'ডিজিটাল স্ক্রিপ্ট',
                'verbose_name_plural': 'ডিজিটাল স্ক্রিপ্টসমূহ',
                'indexes': [models.Index(fields=['script_date'], name='scripts_scr_script__cfe9b1_idx'), models.Index(fields=['status'], name='scripts_scr_status_3bcf2e_idx'), models.Index(fields=['writer', 'status'], name='scripts_scr_writer__a792fe_idx')],
            },
        ),
    ]
