# Generated by Django 5.2.16 on 2026-07-21 00:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scripts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='script',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='script',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='script',
            name='script_date',
            field=models.DateField(db_index=True, verbose_name='তারিখ'),
        ),
        migrations.AlterField(
            model_name='script',
            name='source',
            field=models.CharField(choices=[('district', 'জেলা'), ('reuters', 'রয়টার্স'), ('social', 'সোশ্যাল মিডিয়া'), ('studio', 'স্টুডিও শুটিং')], db_index=True, max_length=20, verbose_name='কন্টেন্ট সোর্স'),
        ),
        migrations.AlterField(
            model_name='script',
            name='status',
            field=models.CharField(choices=[('draft', 'খসড়া'), ('pending', 'অনুমোদনের অপেক্ষায়'), ('approved', 'অনুমোদিত')], db_index=True, default='draft', max_length=20, verbose_name='স্ট্যাটাস'),
        ),
        migrations.AddIndex(
            model_name='script',
            index=models.Index(fields=['-script_date', '-created_at'], name='scripts_scr_script__935d5e_idx'),
        ),
    ]
