# Generated by Django 5.2.16 on 2026-07-21 02:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0003_alter_assignment_assign_date_and_more'),
        ('scripts', '0002_alter_script_created_at_alter_script_deleted_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='script',
            name='assignment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scripts', to='assignments.assignment', verbose_name='এসাইনমেন্ট'),
        ),
    ]
