# Generated by Django 5.2.16 on 2026-07-21 02:10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scripts', '0003_add_assignment_to_script'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScriptEditHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('headline', models.CharField(max_length=255, verbose_name='সম্ভাব্য হেডলাইন')),
                ('body', models.TextField(blank=True, default='', verbose_name='স্ক্রিপ্ট')),
                ('change_summary', models.TextField(blank=True, default='', verbose_name='পরিবর্তনের সারাংশ')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('editor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='script_edits', to=settings.AUTH_USER_MODEL, verbose_name='সম্পাদক')),
                ('script', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edit_history', to='scripts.script', verbose_name='স্ক্রিপ্ট')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'স্ক্রিপ্ট সম্পাদনা ইতিহাস',
                'verbose_name_plural': 'স্ক্রিপ্ট সম্পাদনা ইতিহাসসমূহ',
                'ordering': ['-created_at'],
            },
        ),
    ]
