# Generated by Django 5.2.16 on 2026-07-23 06:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0005_alter_assignment_options_and_more'),
        ('scripts', '0004_add_script_edit_history'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='script',
            options={'verbose_name': 'Digital Script', 'verbose_name_plural': 'Digital Scripts'},
        ),
        migrations.AlterModelOptions(
            name='scriptedithistory',
            options={'ordering': ['-created_at'], 'verbose_name': 'Script Edit History', 'verbose_name_plural': 'Script Edit Histories'},
        ),
        migrations.AlterField(
            model_name='script',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Approval Time'),
        ),
        migrations.AlterField(
            model_name='script',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_scripts', to=settings.AUTH_USER_MODEL, verbose_name='Approver'),
        ),
        migrations.AlterField(
            model_name='script',
            name='assignment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scripts', to='assignments.assignment', verbose_name='Assignment'),
        ),
        migrations.AlterField(
            model_name='script',
            name='body',
            field=models.TextField(blank=True, default='', verbose_name='Script'),
        ),
        migrations.AlterField(
            model_name='script',
            name='district',
            field=models.CharField(blank=True, db_index=True, default='', max_length=100, verbose_name='District Name'),
        ),
        migrations.AlterField(
            model_name='script',
            name='district_reporter',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='District Reporter'),
        ),
        migrations.AlterField(
            model_name='script',
            name='headline',
            field=models.CharField(max_length=255, verbose_name='Possible Headlines'),
        ),
        migrations.AlterField(
            model_name='script',
            name='script_date',
            field=models.DateField(db_index=True, verbose_name='The Date'),
        ),
        migrations.AlterField(
            model_name='script',
            name='source',
            field=models.CharField(choices=[('district', 'District'), ('reuters', 'Reuters'), ('social', 'Social Media'), ('studio', 'Studio Shooting')], db_index=True, max_length=20, verbose_name='Content Source'),
        ),
        migrations.AlterField(
            model_name='script',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending', 'Awaiting Approval'), ('approved', 'Approved')], db_index=True, default='draft', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='script',
            name='writer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scripts', to=settings.AUTH_USER_MODEL, verbose_name='Script Writer'),
        ),
        migrations.AlterField(
            model_name='scriptedithistory',
            name='body',
            field=models.TextField(blank=True, default='', verbose_name='Script'),
        ),
        migrations.AlterField(
            model_name='scriptedithistory',
            name='change_summary',
            field=models.TextField(blank=True, default='', verbose_name='Summary Of Changes'),
        ),
        migrations.AlterField(
            model_name='scriptedithistory',
            name='editor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='script_edits', to=settings.AUTH_USER_MODEL, verbose_name='Editor'),
        ),
        migrations.AlterField(
            model_name='scriptedithistory',
            name='headline',
            field=models.CharField(max_length=255, verbose_name='Possible Headlines'),
        ),
        migrations.AlterField(
            model_name='scriptedithistory',
            name='script',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edit_history', to='scripts.script', verbose_name='Script'),
        ),
    ]
