# Generated by Django 5.2.16 on 2026-07-25 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scripts', '0005_alter_script_options_alter_scriptedithistory_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='script',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='script',
            name='hashtags',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='Hashtags'),
        ),
        migrations.AddField(
            model_name='script',
            name='keywords',
            field=models.TextField(blank=True, default='', verbose_name='Keywords'),
        ),
        migrations.AddField(
            model_name='script',
            name='reporter_name',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Reporter Name'),
        ),
        migrations.AddField(
            model_name='script',
            name='special_note',
            field=models.TextField(blank=True, default='', verbose_name='Special Note'),
        ),
    ]
