# Generated by Django 5.2.16 on 2026-07-25 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scripts', '0006_script_description_script_hashtags_script_keywords_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='script',
            options={'ordering': ['-script_date', '-created_at'], 'verbose_name': 'Digital Script', 'verbose_name_plural': 'Digital Scripts'},
        ),
    ]
