# Generated by Django 5.2.16 on 2026-07-21 02:41

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assignments', '0003_alter_assignment_assign_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FinalPackage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('package_date', models.DateField(db_index=True, verbose_name='তারিখ')),
                ('title', models.CharField(max_length=255, verbose_name='শিরোনাম')),
                ('producer', models.CharField(blank=True, default='', max_length=255, verbose_name='প্রযোজক')),
                ('editor', models.CharField(blank=True, default='', max_length=255, verbose_name='সম্পাদক')),
                ('runtime', models.CharField(blank=True, default='', max_length=20, verbose_name='দৈর্ঘ্য')),
                ('file_link', models.URLField(blank=True, default='', max_length=500, verbose_name='ফাইল লিংক')),
                ('notes', models.TextField(blank=True, default='', verbose_name='নোট')),
                ('status', models.CharField(choices=[('draft', 'খসড়া'), ('complete', 'সম্পূর্ণ'), ('approved', 'অনুমোদিত')], db_index=True, default='draft', max_length=20, verbose_name='স্ট্যাটাস')),
                ('assignment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='final_packages', to='assignments.assignment', verbose_name='এসাইনমেন্ট')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='final_packages', to=settings.AUTH_USER_MODEL, verbose_name='যোগকারী')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ফাইনাল প্যাকেজ',
                'verbose_name_plural': 'ফাইনাল প্যাকেজসমূহ',
                'indexes': [models.Index(fields=['package_date'], name='finalpackag_package_2bde08_idx'), models.Index(fields=['status'], name='finalpackag_status_ff0ff4_idx'), models.Index(fields=['-package_date', '-created_at'], name='finalpackag_package_556bd7_idx')],
            },
        ),
    ]
