# Generated by Django 5.2.16 on 2026-07-23 07:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0005_alter_assignment_options_and_more'),
        ('finalpackage', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='finalpackage',
            options={'verbose_name': 'The Final Package', 'verbose_name_plural': 'Final Packages'},
        ),
        migrations.AddField(
            model_name='finalpackage',
            name='editor_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='edited_packages', to=settings.AUTH_USER_MODEL, verbose_name='Editor (User)'),
        ),
        migrations.AddField(
            model_name='finalpackage',
            name='video_link',
            field=models.URLField(blank=True, default='', max_length=500, verbose_name='Video Content Link'),
        ),
        migrations.AddField(
            model_name='finalpackage',
            name='voice_link',
            field=models.URLField(blank=True, default='', max_length=500, verbose_name='Voice Recording Link'),
        ),
        migrations.AlterField(
            model_name='finalpackage',
            name='assignment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='final_packages', to='assignments.assignment', verbose_name='Assignment'),
        ),
        migrations.AlterField(
            model_name='finalpackage',
            name='editor',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Editor'),
        ),
        migrations.AlterField(
            model_name='finalpackage',
            name='file_link',
            field=models.URLField(blank=True, default='', max_length=500, verbose_name='File Link'),
        ),
        migrations.AlterField(
            model_name='finalpackage',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='final_packages', to=settings.AUTH_USER_MODEL, verbose_name='Adder'),
        ),
        migrations.AlterField(
            model_name='finalpackage',
            name='notes',
            field=models.TextField(blank=True, default='', verbose_name='Note'),
        ),
        migrations.AlterField(
            model_name='finalpackage',
            name='package_date',
            field=models.DateField(db_index=True, verbose_name='The Date'),
        ),
        migrations.AlterField(
            model_name='finalpackage',
            name='producer',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='The Producer'),
        ),
        migrations.AlterField(
            model_name='finalpackage',
            name='runtime',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Length'),
        ),
        migrations.AlterField(
            model_name='finalpackage',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('complete', 'Complete'), ('approved', 'Approved')], db_index=True, default='draft', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='finalpackage',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Title'),
        ),
    ]
