# Generated by Django 5.2.16 on 2026-07-25 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finalpackage', '0002_alter_finalpackage_options_finalpackage_editor_user_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='finalpackage',
            options={'ordering': ['-package_date', '-created_at'], 'verbose_name': 'The Final Package', 'verbose_name_plural': 'Final Packages'},
        ),
    ]
