# Generated by Django 5.2.16 on 2026-07-18 14:02

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('notification_type', models.CharField(choices=[('assignment', 'এসাইনমেন্ট'), ('script_submit', 'স্ক্রিপ্ট সাবমিট'), ('script_approve', 'স্ক্রিপ্ট অনুমোদন'), ('script_reject', 'স্ক্রিপ্ট বাতিল'), ('notice', 'নোটিশ'), ('registration', 'রেজিস্ট্রেশন'), ('welcome', 'স্বাগতম')], max_length=30, verbose_name='ধরণ')),
                ('title', models.CharField(max_length=255, verbose_name='শিরোনাম')),
                ('message', models.TextField(blank=True, verbose_name='বার্তা')),
                ('link', models.CharField(blank=True, max_length=500, verbose_name='লিঙ্ক')),
                ('is_read', models.BooleanField(default=False, verbose_name='পড়া হয়েছে')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='পড়ার সময়')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'নোটিফিকেশন',
                'verbose_name_plural': 'নোটিফিকেশন',
                'ordering': ['-created_at'],
            },
        ),
    ]
