# Generated by Django 5.2.16 on 2026-07-25 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_alter_devicetoken_is_active_alter_devicetoken_token_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='devicetoken',
            options={'verbose_name': 'Device Token', 'verbose_name_plural': 'Device Token'},
        ),
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-created_at'], 'verbose_name': 'Notification', 'verbose_name_plural': 'Notification'},
        ),
        migrations.AlterField(
            model_name='notification',
            name='is_read',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Has Been Read'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='link',
            field=models.CharField(blank=True, max_length=500, verbose_name='Link'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='message',
            field=models.TextField(blank=True, verbose_name='The Message'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('Assignment', 'Assignment'), ('Script_Submit', 'Script Submit'), ('Script_Approve', 'Script Approval'), ('Script_Reject', 'Script Rejected'), ('Notice', 'Notice'), ('Registration', 'Registration'), ('Welcome', 'Swagtam')], db_index=True, max_length=30, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='read_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Reading Time'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Title'),
        ),
    ]
