# Generated by Django 5.2.16 on 2026-07-25 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_alter_devicetoken_options_alter_notification_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='devicetoken',
            options={'ordering': ['-created_at'], 'verbose_name': 'Device Token', 'verbose_name_plural': 'Device Token'},
        ),
    ]
