# Generated by Django 5.2.16 on 2026-08-03 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0005_add_model_ordering'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('Notice', 'Notice'), ('Registration', 'Registration'), ('Welcome', 'Swagtam')], db_index=True, max_length=30, verbose_name='Type'),
        ),
    ]
